#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use thermo_pw.x to check the convergence"
$ECHO "of the total energy with the kinetic energy cut-off."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Cu.pz-dn-rrkjus_psl.1.0.0.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
GP_COMMAND=`which gnuplot 2>/dev/null`
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO "  running gnuplot as: $GP_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/silicon*
$ECHO " done"

cat > si.scf_ke.in << EOF
 &INPUT_THERMO
  what='scf_ke',
  deltake=10.0,
  nke=8
  nkeden=1
  deltakeden=100.0,
 /
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='copper',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav=  2, 
    celldm(1) =6.82, 
    nat=  1, 
    ntyp= 1,
    smearing='mp'
    degauss=0.02,
    occupations='smearing'
    ecutwfc =40.0,
    ecutrho =300,
 /
 &electrons
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Cu  0.0  Cu.pz-dn-rrkjus_psl.1.0.0.UPF
ATOMIC_POSITIONS
 Cu 0.00 0.00 0.00
K_POINTS AUTOMATIC
4 4 4 1 1 1 
EOF
$ECHO "  running the scf calculation checking the ke cut-off and"
$ECHO "  creating the postscript file output_keconv.ps...\c"
$THERMO_PW_COMMAND < si.scf_ke.in > si.scf_ke.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
