#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example applies thermo_pw.x to sic a solid with the b3 structure"
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Si.pz-nl-kjpaw_psl.1.0.0.UPF  C.pz-n-kjpaw_psl.1.0.0.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/bands" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/bands

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g1/sic*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='scf_bands',
  nbnd_bands=12,
  emax_input=7.0
 /
EOF

cat > sic.scf.in << EOF
 &control
    calculation = 'scf'
    prefix='sic',
    pseudo_dir = '$PSEUDO_DIR',
    outdir='$TMP_DIR'
 /
 &system
   ibrav=  2, 
   celldm(1) =8.1831, 
   nat= 2, 
   ntyp=2,
   noncolin=.false.,
   lspinorb=.false.,
   ecutwfc =40,
   ecutrho =300,
 /
 &electrons
    conv_thr =  1.0d-10
 /
ATOMIC_SPECIES
Si  0.0   Si.pz-nl-kjpaw_psl.1.0.0.UPF
C   0.0   C.pz-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS alat
Si  0.0000      0.000000    0.000000
C   0.2500000   0.2500000   0.2500000
K_POINTS AUTOMATIC
4 4 4 1 1 1
EOF

$ECHO "  running the scf calculation for SiC...\c"
$THERMO_PW_COMMAND < sic.scf.in > sic.scf.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
