#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use thermo_pw.x to calculate the"
$ECHO "lattice constant, bulk modulus, and other anharmonic properties"
$ECHO "of silicon as a function of the temperature. It uses the "
$ECHO "quasi-static elastic constants to compute the bulk modulus as"
$ECHO "a function of temperature."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x plotband.x"
PSEUDO_LIST="Si.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"


# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done

for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results
cp -r ../../example22/reference/elastic_constants/ .

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/silicon*
rm -rf $TMP_DIR/g*/_ph*/silicon*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='mur_lc_t',
  deltat=3.,
  lmurn=.FALSE.
 /
EOF

cat > si.mur_lc_t.in << EOF

 &control
   calculation = 'scf'
   prefix='silicon',
   pseudo_dir = '$PSEUDO_DIR/',
   outdir='$TMP_DIR/'
 /
 &system
   ibrav= 2, 
   celldm(1)= 10.20, 
   nat=2, 
   ntyp=1,
   ecutwfc=24.0,
 /
 &electrons
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS (alat)
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS AUTOMATIC
2 2 2 1 1 1 
EOF

cat > ph_control << EOF
ph_title
 &inputph
  tr2_ph=1.0d-12,
  prefix='silicon',
  fildyn='si.dyn.xml',
  ldisp=.TRUE.
  nq1=4, nq2=4, nq3=4,
/
EOF

$ECHO " "
$ECHO " This is the thermo mur_lc_t calculation for Si"
$ECHO " whereby the files of elastic constants computed at"
$ECHO " different geometries are present in the directory"
$ECHO " elastic_constants, given by example22."
$ECHO " Quasi-static isothermal and adiabatic elastic constants and"
$ECHO " bulk modulus are in output_anhar.el_cons.ps."
$ECHO " Quasi-static isothermal and adiabatic elastic compliances and"
$ECHO " compressibility are in output_anhar.el_comp.ps."
$ECHO " Thermal stresses are in output_tstress.ps."
$ECHO " Generalized average Gruneisen parameter is in output_anhar.ggamma.ps."
$ECHO " The other quantities are analogous to those presented in example09"
$ECHO " but anharmonic quantities are also derived from Gruneisen parameters"
$ECHO " with a bulk modulus obtained from elastic compliances."
$ECHO " Running..."

$THERMO_PW_COMMAND < si.mur_lc_t.in > si.mur_lc_t.out
check_failure $?
$ECHO " done"
$ECHO
$ECHO "$EXAMPLE_DIR: done"

