#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use thermo_pw.x to calculate"
$ECHO "the electronic thermodynamic properties of Aluminum on a mesh"
$ECHO "of geometries."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Al.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results_mur_lc" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results_mur_lc

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/aluminum*
rm -rf $TMP_DIR/g*/_ph*/aluminum*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='mur_lc',
  frozen_ions=.FALSE.
  lel_free_energy=.TRUE.
  nk1_d=16
  nk2_d=16
  nk3_d=16
  nbnd_bands=12
 /
EOF

cat > al.mur_lc.in << EOF
 &control
   calculation = 'scf'
   prefix='aluminum',
   pseudo_dir = '$PSEUDO_DIR/',
   outdir='$TMP_DIR/'
 /
 &system
    ibrav=  2, 
    celldm(1) =7.50, 
    nat=  1, 
    ntyp= 1,
    smearing='mp'
    degauss=0.02,
    occupations='smearing'
    ecutwfc =16.0,
 /
 &electrons
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Al  0.0  Al.pz-vbc.UPF
ATOMIC_POSITIONS (alat)
 Al 0.00 0.00 0.00
K_POINTS AUTOMATIC
8 8 8 1 1 1 
EOF


$ECHO "  Running thermo mur_lc with lel_free_energy=.TRUE. " 
$ECHO "  to compute the electronic thermodynamic properties at each "
$ECHO "  reference geometry. These quantities are written in the "
$ECHO "  therm_files directory.\c"

$THERMO_PW_COMMAND < al.mur_lc.in > al.mur_lc.out
check_failure $?
$ECHO " done"
$ECHO ""

$ECHO
$ECHO "$EXAMPLE_DIR : done"
