#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO " This example shows how to use thermo_pw.x to calculate"
$ECHO " the anharmonic properties of Aluminum keeping into"
$ECHO " account the contribution of the electronic exitations "
$ECHO " to the thermodynamic properties."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Al.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results_mur_lc_t" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results_mur_lc_t

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/aluminum*
rm -rf $TMP_DIR/g*/_ph*/aluminum*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='mur_lc_t',
  deltat=3.,
  lmurn=.FALSE.
  lel_free_energy=.TRUE.
 /
EOF

cat > ph_control << EOF
ph_title
 &inputph
  tr2_ph=1.0d-12,
  prefix='aluminum',
  fildyn='al.dyn.xml',
  ldisp=.TRUE.
  nq1=2, nq2=2, nq3=2,
/
EOF

$ECHO " running the thermo mur_lc_t calculation for aluminum,"
$ECHO " the electronic exitation free energy is added to the "
$ECHO " free energy. These quantities must be already on file"
$ECHO " and are calculated in a preliminary run with what='mur_lc'"
$ECHO " phonon dispersions can be found in output_disp.g#.ps,"
$ECHO " phonon_dos in output_dos.g#.ps,"
$ECHO " harmonic thermodynamic properties in output_therm.g#.ps,"
$ECHO " anharmonic thermodynamic properties in output_anhar.ps...\c"
$ECHO " Running..."

cp ../results_mur_lc/al.mur_lc.in ./al.mur_lc.in
cp -R ../results_mur_lc/therm_files/ .

$THERMO_PW_COMMAND < al.mur_lc.in > al.mur_lc.out

$ECHO
$ECHO "$EXAMPLE_DIR : done"
