#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example runs thermo_pw on a solid with space group 31 (Cu3AsS4)"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST=""

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/res_31_cu3ass4" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/res_31_cu3ass4

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/cu3ass4*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='plot_bz',
 /
EOF

cat > cu3ass4.scf_bands.in << EOF
 &control
  calculation = 'scf'
  prefix='cu3ass4',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'
  verbosity='high'
 /
 &system
  ibrav  = 8
  celldm(1)=14.0407
  celldm(2)= 0.869448183042 
  celldm(3)= 0.831763122476 
  space_group=31,
  nat           = 6,
  ntyp          = 3,
  ecutwfc =45.0,
  ecutrho =300.,
!  lspinorb=.TRUE.
!  noncolin=.TRUE.
!  nspin=2
  occupations='smearing'
  smearing='mp'
  degauss=0.02
!  starting_magnetization(1)=0.2
 /
 &electrons
  conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
Cu  0.0  Cu.pz-dn-kjpaw_psl.1.0.0.UPF
As  0.0  As.pz-n-kjpaw_psl.1.0.0.UPF
S   0.0  S.pz-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS crystal_sg
As 2a  0.82680 0.00000
Cu 2a  0.15140 0.49830
Cu 4b  0.24660 0.32550 -0.01340
S  2a  0.82260 0.64540
S  2a  0.14360 0.11660
S  4b  0.25980 0.33640 0.61840
K_POINTS AUTOMATIC
2 2 2 1 1 1 
EOF
$ECHO "  running the scf_bands calculation for high Cu3AsS4..."
$THERMO_PW_COMMAND < cu3ass4.scf_bands.in > cu3ass4.scf_bands.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
