#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example runs thermo_pw on a solid with space group 162 (V2N)"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST=""

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/res_141_v2h" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/res_141_v2h

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

#$ECHO "  cleaning $TMP_DIR...\c"
#rm -rf $TMP_DIR/g*/v2h*
#$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='scf_bands',
  only_bands_plot=.TRUE.
 /
EOF

cat > v2h.scf_bands.in << EOF
 &control
  calculation = 'scf'
  prefix='v2h',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'
  verbosity='high'
 /
 &system
  ibrav         = 7,
  celldm(1)     = 11.142146717855999,
  celldm(3)     = 1.130882444,
  nat           = 12,
  ntyp          = 2,
  ecutwfc =30.0,
  ecutrho =200.,
!  lspinorb=.TRUE.
!  noncolin=.TRUE.
!  nspin=2
  occupations='smearing'
  smearing='mp'
  degauss=0.02
!  starting_magnetization(1)=0.2
 /
 &electrons
  conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 H  0.0  H.pz-kjpaw_psl.1.0.0.UPF
 V  0.0  V.pz-spn-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS crystal
V        0.501299916   0.229133691   0.730433607
V        0.998700084   0.731733524   0.730433607
V        0.001299916   0.730433607   0.229133691
V        0.498700084   0.730433607   0.731733524
V        0.001299916   0.268266476   0.269566393
V        0.498700084   0.770866309   0.269566393
V        0.998700084   0.269566393   0.770866309
V        0.501299916   0.269566393   0.268266476
H        0.500000000   0.500000000   0.000000000
H        0.000000000   0.000000000   0.000000000
H        0.500000000   0.000000000   0.000000000
H        0.000000000   0.000000000   0.500000000
K_POINTS AUTOMATIC
2 2 2 1 1 1 
EOF
$ECHO "  running the scf_bands calculation for V2H..."
$THERMO_PW_COMMAND < v2h.scf_bands.in > v2h.scf_bands.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
