#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example runs thermo_pw on a solid with space group 63 (U)"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST=""

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/res_63_u" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/res_63_u

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/u*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='plot_bz',
 /
EOF

cat > u.scf_bands.in << EOF
 &control
  calculation = 'scf'
  prefix='u',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'
  verbosity='high'
 /
 &system
  ibrav=9
  celldm(1) = 5.3751,
  celldm(2) = 2.06331739558 
  celldm(3) = 1.73379271551
  space_group=63
  nat=  1, 
  ntyp= 1,
  ecutwfc =45.0,
  ecutrho = 350.,
!  lspinorb=.TRUE.
!  noncolin=.TRUE.
!  nspin=2
  occupations='smearing'
  smearing='mp'
  degauss=0.02
!  starting_magnetization(1)=0.2
 /
 &electrons
  conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 U   0.0  U.pz-spfn-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS crystal_sg
U   4c  0.10228
Cr  4c  0.85475
K_POINTS AUTOMATIC
4 4 4 1 1 1 
EOF
$ECHO "  running the scf_bands calculation for U..."
$THERMO_PW_COMMAND < u.scf_bands.in > u.scf_bands.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
