#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example runs thermo_pw on a solid with space group 43 (GeS2)"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST=""

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done

for DIR in "$TMP_DIR" "$EXAMPLE_DIR/res_43_ges2" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/res_43_ges2

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/ges2*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='plot_bz',
 /
EOF

cat > ges2.scf_bands.in << EOF
 &control
  calculation = 'scf'
  prefix='ges2',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'
  verbosity='high'
 /
 &system
  ibrav  = 10
  celldm(1) = 22.034
  celldm(2) = 1.91595197256 
  celldm(3) = 0.58833619211
  space_group=43,
  nat           = 5,
  ntyp          = 2,
  ecutwfc =45.0,
  ecutrho =300.,
!  lspinorb=.TRUE.
!  noncolin=.TRUE.
!  nspin=2
  occupations='smearing'
  smearing='mp'
  degauss=0.02
  nr1=144,
  nr2=144,
  nr3=144,
!  starting_magnetization(1)=0.2
 /
 &electrons
  conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
Ge   0.0  Ge.pz-dn-kjpaw_psl.1.0.0.UPF
S   0.0   S.pz-nl-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS crystal_sg
Ge 8a    0.00000
Ge 16b  0.12500   0.13900   0.00000
S  16b  0.02200   0.08000   0.18300
S  16b  0.15200  -0.01400  -0.18300
S  16b  0.06200   0.12500  -0.27800
K_POINTS AUTOMATIC
2 2 2 1 1 1 
EOF
$ECHO "  running the scf_bands calculation for GeS2..."
$THERMO_PW_COMMAND < ges2.scf_bands.in > ges2.scf_bands.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
