#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example runs thermo_pw on a solid with space group 121 (Cu2FeS4Sn)"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST=""

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/res_121_cu2fes4sn" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/res_121_cu2fes4sn

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
THERMO_PW_COMMAND="$PARA_IMAGE_PREFIX $BIN_DIR/thermo_pw.x $PARA_IMAGE_POSTFIX"
# check for gnuplot
$ECHO
$ECHO "  running thermo_pw.x as: $THERMO_PW_COMMAND"
$ECHO

$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/g*/cu2fes4sn*
$ECHO " done"

cat > thermo_control << EOF
 &INPUT_THERMO
  what='plot_bz',
 /
EOF

cat > cu2fes4sn.scf_bands.in << EOF
 &control
  calculation = 'scf'
  prefix='cu2fes4sn',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'
  verbosity='high'
 /
 &system
  ibrav=7
  celldm(1)=10.3179,
  celldm(3)=1.96428571429,
  space_group=121
  nat=  4, 
  ntyp= 4,
  ecutwfc =45.0,
  ecutrho = 350.,
  occupations='smearing'
  smearing='mp'
  degauss=0.02
!  lspinorb=.TRUE.
!  noncolin=.TRUE.
!  nspin=2
 /
 &electrons
  conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
Cu   0.0  Cu.pz-dn-kjpaw_psl.1.0.0.UPF 
Fe   0.0  Fe.pz-spn-kjpaw_psl.1.0.0.UPF 
S    0.0  S.pz-n-kjpaw_psl.1.0.0.UPF 
Sn   0.0  Sn.pz-dn-kjpaw_psl.1.0.0.UPF 
ATOMIC_POSITIONS crystal_sg
Fe 2a
Sn 2b 
Cu 4d
S  8i 0.74500 0.36800
K_POINTS AUTOMATIC
4 4 4 1 1 1 
EOF
$ECHO "  running the scf_bands calculation for Cu2FeS4Sn..."
$THERMO_PW_COMMAND < cu2fes4sn.scf_bands.in > cu2fes4sn.scf_bands.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
